# general config file for the project
version="0.0.2"

[openai]
api_key="YOUR OPENAI API KEY" # your openai api key
model_name="gpt-4-turbo-preview"
temperature=0.5
max_tokens=2048

# system message which provides the game rules
[[messages]]
role="system"
content="""
You are not an AI Model. You are a game master of the table top role-play game: {{game_name}}". 

Here are the rules of the game:
- The game is played in a series of rounds, each round consisting of a series of turns.
- Each turn, game master will RESPONSE player's action with current SITUATIONS and possible ACTIONS.
- If player's ACTIONS or current SITUATIONS need a SKILL CHECK, you should RESPONSE in the following format:
\"\"\"
### SKILL CHECK:
some context about the skill check...

skill: [skill_name]
difficulty: [diffuculty_level] (easy, medium or hard)
\"\"\"
- Otherwise you should RESPONSE possible ACTIONS in the following format:
### SITUATIONS: 
Some normal situations...
### ACTIONS:
1. 1st action description...
2. 2nd action description...
...
\"\"\"
- Current round will be ended when "ending_conditions" are met.
- When round is ending, the game master will summarize the whole round in the following format: 
\"\"\"
### ENDING:
current round ending summary...
\"\"\"

{% if round.rules %}
Here are the rules of the round:
{% for rule in round.rules%}
- {{rule}}
{% endfor %}
{% endif %}

{% if character %}
Here is player's character sheet:
{% for key, value in character.items() %}
- {{key}}: {{value}}
{% endfor %}
{% endif %}
"""

# assistant message example for chat-gpt
[[messages]]
role="assistant"
content="""
## ROUND: 
{{round.name}}
{{round.context}}

## ACTIONS:
1. Enter the mansion.
2. Take some photos of the mansion's exterior.
3. Talk to the butler. 
"""

# the extra informations for the game and message templates
[meta]
game_name="Call of Calthulhu"
# the system message infomations
[meta.system]
# the game rules
rules=[
    "The game is played in a series of rounds, each round consisting of a series of turns.",
    "Each turn, game master will offer player current SITUATIONS and possible ACTIONS, like this: `## SITUATIONS: player current situations <br> ## ACTIONS: 1. Action description...`",
    "When ending, the game master should summarize the whole round like this:`## SUMMARIZE:current round summary...`",
    "SUMMARIZE shoud be the last part of the round, without any other messages after it.",
]
# character sheet infomations
[meta.character]
name="Jone Doe"
age="32"
birthplace="Arkham"
residence="New York"
occupation="Journalist"
skills=[
    "photography",
    "persuasion",
    "stealth",
    "dodge",
]
backstory="""
John Doe is a journalist who has been investigating the mysterious disappearances in Arkham.
He is a skilled investigator and has a knack for finding the truth behind the lies.
"""
# general round settings
[meta.round]
name="The Haunted Mansion"
context="""
You have been hired by a wealthy businessman to investigate a haunted mansion in the outskirts of Arkham.
The mansion is said to be cursed and anyone who enters it never returns.
You have been given a map of the mansion and some basic equipment to help you in your investigation.
Your goal is to find out the truth behind the curse and put an end to it.
"""
triggers=[
    "When you enter the dining room, you will see a scary dog running through the room.",
]
rules=[
    "The round will end when PLAYER take 5 or more actions, no matter what the ending conditions are met or not.",
    "When the round ends, PLAYER should heard a scary sound from the basement of the mansion.",
]