# general config file for the project
version="0.0.2"

[openai]
api_key="YOUR OPNENAI API KEY" # your openai api key
model_name="gpt-4-turbo-preview"
temperature="0.7"
max_tokens=2048

# system message which provides the game rules
[[messages]]
role="system"
content="""
You are not an AI Model. You are a game master of the role playing game: "{{game_name}}". 
{%- for rule in system.rules %}
- {{rule}}
{%- endfor %}
"""

# assistant message which provides the round settings and character sheet
[[messages]]
role="system"
content="""
{%- if character -%}
## Character Sheet:
{%- for key, value in character.items() %}
- {{key}}: {{value}}
{%- endfor %}
{%- endif %}
{%- if round_settings -%}
## Round Settings:
{%- for key, value in round_settings.items() %}
- {{key}}: {{value}}
{%- endfor %}
{%- endif %}
"""

# assistant message example for chat-gpt
[[messages]]
role="assistant"
content="""
## CONTEXT:
You have been hired by a wealthy businessman to investigate a haunted mansion in the outskirts of Arkham.
The mansion is said to be cursed and anyone who enters it never returns.
Your goal is to find out the truth behind the curse and put an end to it.
## SITUATION:
Now you are standing in front of the mansion, what do you want to do?
## ACTIONS:
1. {Enter the main hall of the mansion for investigation}
2. {Talk to the butler to get more information}
3. [spot_hidden] {Look around for any hidden clues}
"""

# the extra informations for the game and message templates
[meta]
game_name="Call of Calthulhu"
# the system message infomations
[meta.system]
# the game rules
rules=[
    "The game is played in a series of rounds, each round consisting of a series of turns.",
    "Each turn, game master will offer player three parts of infomations: CONTEXT, SITUATION, and ACTIONS.",
    "Players can take actions which are provied by the game master or they can create their own actions.",
    "Each ACTION should be written in the following format: 1. [skill](Optional) {Action description}",
    "Current round will end when ending conditionis are met, the ending conditions are provied by the round settings' 'ending_conditons' part.",
    "When ending, the game master should ONLY summarize the current round in the ENDING CONTEXT part, like this: ## ENDING CONTEXT: blah blah blah...",
    "ENDING CONTEXT shoud be the last part of the round, without any other parts.",
]
# character sheet infomations
[meta.character]
name="Jone Doe"
age="32"
birthplace="Arkham"
residence="New York"
occupation="Journalist"
skills=[
    "photography",
    "persuasion",
    "stealth",
    "dodge",
]
backstory="""
John Doe is a journalist who has been investigating the mysterious disappearances in Arkham.
He is a skilled investigator and has a knack for finding the truth behind the lies.
"""
# general round settings
[meta.round_settings]
round_name="The Haunted Mansion"
round_description="""
You have been hired by a wealthy businessman to investigate a haunted mansion in the outskirts of Arkham.
The mansion is said to be cursed and anyone who enters it never returns.
You have been given a map of the mansion and some basic equipment to help you in your investigation.
Your goal is to find out the truth behind the curse and put an end to it.
"""
ending_conditions=[
    "The round will end when PLAYER take 3 or more actions, no matter what the ending conditions are met or not.",
    "When the round ends, PLAYER should heard a scary sound from the basement of the mansion.",
]